### ISSUE TITLE
go1.6 support

### ISSUE THREAD

**Issue by shanemhansen** [aarzilli/golua#41]
It looks like golua violates the go1.6 CGO pointer rules.

Test program:

```
L := lua.NewState()
L.OpenLibs()
defer L.Close()
```

output: 

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/aarzilli/golua/lua.newState(0xdb8400, 0x0)
	/home/shansen/src/github.com/aarzilli/golua/lua/lua.go:41 +0x23e
github.com/aarzilli/golua/lua.NewState(0x7f1345e3b078)
	/home/shansen/src/github.com/aarzilli/golua/lua/lauxlib.go:169 +0x25
main.main()
	/home/shansen/src/$snip/main.go:8 +0x18
exit status 2

```

More info about the new rules here: https://tip.golang.org/doc/go1

**Comment by aarzilli** [comment]
Thanks for the heads up.

**Comment by tarndt** [comment]
Thanks for fixing!
