### ISSUE TITLE
mulitple lua_state in each goroutine, will panic

### ISSUE THREAD

**Issue by huangwei1024** [aarzilli/golua#51]
```
func worker() {
	L := lua.NewState()
	defer L.Close()
	L.OpenLibs()
	L.DoFile("./test.lua")
}
func test() {
	count := 1000
	ch := make(chan int, count)
	for i := 0; i < count; i++ {
		go worker()
	}
        // wait all
}
```

if count < 500, it is ok. but bigger count, it will panic. so wired!

**Comment by huangwei1024** [comment]
I found some documents say only one lua_state for each indepent thread is safe. And I try gopher-lua replaced also is ok.
the problem is due to lua? go? or go-lua?

**Comment by Ambrevar** [comment]
Indeed, Lua is not thread-safe, nor is Golua which relies on Lua.

Gopher-lua is written in pure Go and does not suffer from this issue.

Note that with some clever mechanism you can use channels from Golua thus allowing you to synchronize your goroutines.
See [Luar](https://godoc.org/github.com/stevedonovan/luar#example-MakeChan).

**Comment by aarzilli** [comment]
I can't reproduce this. You should post the panic. If I had to hazard a guess, each goroutine here will need a OS thread because of cgo, if test.lua blocks for long enough you will eventually run out of OS threads, or memory, or whatever.

**Comment by huangwei1024** [comment]
go version go1.7.4 linux/386
```
$ /usr/bin/time -v  go run test_lua.go
Count :  500
Done!
        Command being timed: "go run test_lua.go"
        User time (seconds): 11.62
        System time (seconds): 0.07
        Percent of CPU this job got: 328%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:03.56
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 23100
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 59323
        Voluntary context switches: 18091
        Involuntary context switches: 16743
        Swaps: 0
        File system inputs: 0
        File system outputs: 14840
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

when count=600
```
runtime/cgo: runtime/cgo: pthread_create failed: Resource temporarily unavailable
pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=SIGABRT: abort
PC=0xb75c3d40 m=2

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_386.s:1612 +0x1

goroutine 5 [17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_386.s:1612 +0x1

goroutine 5 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_lua_pcall(0xb7b0d1e0, 0x0, runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_lua_pcall(0xb7b0d1e0, 0x0, 0xffffffff, 0x1, 0x0)
        ??:0 +0xffffffff, 0x1, 0x0)
        ??:0 +0x3f
_/home/huangwei/report/lua.(*State).pcall(0x97360280, 0x0, 0xffffffff, 0x1, 0x3f
_/home/huangwei/report/lua.(*State).pcall(0x97360280, 0x0, 0xffffffff, 0x1, 0x84d016d0)
        /home/huangwei/report/lua/lua.go:180 +0x7f
_/home/huangwei/report/lua.(*State).callEx(0x973602800x84d016d0)
        /home/huangwei/report/lua/lua.go:180 +0x7f
_/home/huangwei/report/lua.(*State).callEx(0x97360280, 0x0, 0xffffffff, 0x84d01601, 0x0, 0x0)
, 0x0, 0xffffffff, 0x84d01601, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:199 +0xc4
_/home/huangwei/report/lua.(*State).Call(0x97360280,    /home/huangwei/report/lua/lua.go:199 +0xc4
_/home/huangwei/report/lua.(*State).Call(0x97360280, 0x0, 0xffffffff, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:2120x0, 0xffffffff, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:212 +0x42
_/home/huangwei/report/lua.(*State).DoFile(0x97360280, 0xb76ba39d, 0xa,  +0x42
_/home/huangwei/report/lua.(*State).DoFile(0x97360280, 0xb76ba39d, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:99 +0x139
0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:99 +0x139
main.worker(0x97360280, 0x9736aa00)
        /home/huangwei/report/test_lua.go:44 +0x64main.worker(0x97360280, 0x9736aa00)
        /home/huangwei/report/test_lua.go:44 +0x64
created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

goroutine 6 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_lua_pcall(0xb7b0df58
goroutine 6 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_lua_pcall(0xb7b0df58, 0x0, 0xffffffff, 0x1, 0x0)
        ??, 0x0, 0xffffffff, 0x1, 0x0)
        ??:0 +0x3f
_/home/huangwei/report/lua.(*State).pcall(0x973602c0, 0x0, :0 +0x3f
_/home/huangwei/report/lua.(*State).pcall(0x973602c0, 0x0, 0xffffffff, 0x1, 0xb7b0d008)
        /home/huangwei/report/lua/lua.go:180 +0x7f0xffffffff, 0x1, 0xb7b0d008)
        /home/huangwei/report/lua/lua.go:180 +0x7f
_/home/huangwei/report/lua.(*State).callEx(0x973602c0, 0x0, 0xffffffff, 0xb7b0d001, 
_/home/huangwei/report/lua.(*State).callEx(0x973602c0, 0x0, 0xffffffff, 0xb7b0d001, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:199 +0xc4
0x0, 0x0)
        /home/huangwei/report/lua/lua.go:199 +0xc4
_/home/huangwei/report/lua.(*State).Call(0x973602c0, 0x0, 0xffffffff, 0x0, 0x0)
_/home/huangwei/report/lua.(*State).Call(0x973602c0, 0x0, 0xffffffff, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:212 +0x42
_/home/huangwei/report/lua.(*State).DoFile(0x973602c0, 0xb76ba39d       /home/huangwei/report/lua/lua.go:212 +0x42
_/home/huangwei/report/lua.(*State).DoFile(0x973602c0, 0xb76ba39d, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:99 +, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:99 +0x139
main.worker(0x973602c0, 0x9736aa00)
        /home/huangwei/report/test_lua.go:0x139
main.worker(0x973602c0, 0x9736aa00)
        /home/huangwei/report/test_lua.go:44 +0x64
created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

goroutine 7 [runnable, locked to thread]:
44 +0x64
created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

goroutine 7 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_luaL_loadfile(0xb7b0ec70, 0x84a061a8, 0x0)
        ??_/home/huangwei/report/lua._Cfunc_luaL_loadfile(0xb7b0ec70, 0x84a061a8, 0x0)
        ??:0 +0x3b
_/home/huangwei/report/lua.(*State).LoadFile(0x97360300, 0xb76ba39d, 0xa, 0x0)
        /home/huangwei/report/lua/lauxlib.go:149 +0xc2
_/home/huangwei/report/lua.(*State).DoFile:0 +0x3b
_/home/huangwei/report/lua.(*State).LoadFile(0x97360300, 0xb76ba39d, 0xa, 0x0)
        /home/huangwei/report/lua/lauxlib.go:149 +0xc2
_/home/huangwei/report/lua.(*State).DoFile(0x97360300, 0xb76ba39d, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:96 +0x3f
main.worker(0x97360300, 0x9736aa00)
        /home/huangwei/report/test_lua.go:44 +0x64
created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

goroutine 8 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_lua_pcall(0xb7b0f988, 0x0, 0xffffffff, 0x1, 0x0)
        ??:0 +0x3f
_/home/huangwei/report/lua.(*State).pcall(0x97360340, 0x0, 0xffffffff, 0x1, 0x84b061a8)
        /home/huangwei/report/lua/lua.go:(0x97360300, 0xb76ba39d, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:96 +0x3f
main.worker(0x97360300, 0x9736aa00)
        /home/huangwei/report/test_lua.go:44 +0x64
created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

goroutine 8 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_lua_pcall(0xb7b0f988, 0x0, 0xffffffff, 0x1, 0x0)
        ??:0 +0x3f
_/home/huangwei/report/lua.(*State).pcall(0x97360340, 0x0, 0xffffffff, 0x1, 0x84b061a8)
        /home/huangwei/report/lua/lua.go:180 +0x7f
_/home/huangwei/report/lua.(*State).callEx(0x97360340, 0x0, 0xffffffff, 180 +0x7f
_/home/huangwei/report/lua.(*State).callEx(0x97360340, 0x0, 0xffffffff, 0x84b06101, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:199 +0xc40x84b06101, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:199 +0xc4
_/home/huangwei/report/lua.(*State).Call(0x97360340, 0x0, 0xffffffff, 0x0, 
_/home/huangwei/report/lua.(*State).Call(0x97360340, 0x0, 0xffffffff, 0x0, 0x0)
        /home/huangwei/report/lua/lua.go:212 +0x42
_/home/huangwei/report/lua.(*State).DoFile(0x0)
        /home/huangwei/report/lua/lua.go:212 +0x42
_/home/huangwei/report/lua.(*State).DoFile(0x97360340, 0xb76ba39d, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go0x97360340, 0xb76ba39d, 0xa, 0x0, 0x0)
        /home/huangwei/report/lua/lauxlib.go:99 +0x139
main.worker(0x97360340, 0x9736aa00)
:99 +0x139
main.worker(0x97360340, 0x9736aa00)
        /home/huangwei/report/test_lua.go:44 +0x64
created by main.test2
                /home/huangwei/report/test_lua.go:44 +0x64
created by main.test2
        /home/huangwei/report/test_lua.go:75 +0x1c6

goroutine 9 [runnable, locked to thread]:
_/home/huangwei/report/lua._Cfunc_luaL_loadfile(0xb7b106a0, 0x84a05ad0/home/huangwei/report/test_lua.go:75 +0x1c6
....skip...

Command exited with non-zero status 1
        Command being timed: "go run test_lua.go"
        User time (seconds): 8.38
        System time (seconds): 0.11
        Percent of CPU this job got: 307%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.76
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 22940
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 59561
        Voluntary context switches: 9869
        Involuntary context switches: 30845
        Swaps: 0
        File system inputs: 0
        File system outputs: 11872
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```

it is cgo problem?

**Comment by huangwei1024** [comment]
it is test.lua

```
local main = {}


main.testFunction = function ()

        local ret = 0
        for i = 1, 1000 do
                if i == 10 then
                        ret = ret + i * 2
                else
                        ret = ret + i
                end
        end
        return ret
end

main.main = function ()
        local ret = 0
        for i = 1, 1000 do
                ret = ret + main.testFunction()
        end
        --print("ret = ", ret)
end

main.main()
```

**Comment by aarzilli** [comment]
> it is cgo problem?

It's limitation of cgo, you are just running out of virtual memory since you are on 32bit linux, this would happen later on 64bit.
